[package]
name = "rustyjam"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.5.0", features = ["dynamic"] }
bevy-inspector-egui = "0.6.1"
bevy_rapier2d = {version = "0.10.2", features = ["simd-stable", "render"] }
bevy_prototype_debug_lines = { git = "https://github.com/Toqozz/bevy_debug_lines"}