name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        strategy:
            matrix:
                toolchain: [stable, nightly]
                os: [windows-latest, ubuntu-latest]
                exclude:
                    - os: windows-latest
                      toolchain: nightly
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v2
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ${{ runner.os }}-cargo-build-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.toml') }}
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ matrix.toolchain }}
                  override: true
            - name: Install alsa and udev
              run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
              if: runner.os == 'linux'
            - name: Build & run tests
              run: cargo test --workspace
              env:
                  CARGO_INCREMENTAL: 0
                  RUSTFLAGS: "-C debuginfo=0 -D warnings"

    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v2
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ${{ runner.os }}-cargo-ci-${{ hashFiles('**/Cargo.toml') }}
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  components: rustfmt, clippy
                  override: true
            - name: Install alsa and udev
              run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
            #- name: FMT project
            #  run: cargo fmt --all -- --check
            #- name: Check with Clippy
            #  run: cargo clippy --workspace --all-targets --all-features -- -D warnings -A clippy::type_complexity
            - name: Build files
              run: cargo build --release --all-features

    build-wasm:
        strategy:
            matrix:
                toolchain: [stable, nightly]
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v2
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ${{ runner.os }}-cargo-build-wasm-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.toml') }}
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ matrix.toolchain }}
                  target: wasm32-unknown-unknown
                  override: true
            - name: Check wasm
              uses: actions-rs/cargo@v1
              with:
                  command: check
                  args: --target wasm32-unknown-unknown --no-default-features --features bevy_winit,x11,hdr,bevy_gltf
